pr:
  - master

variables:
  TF_ROOT: terraform

jobs:
  - job: terraform_plan_json
    displayName: Terraform plan JSON
    pool:
      vmImage: ubuntu-latest

    steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform

      - bash: terraform plan -out tfplan.binary
        displayName: Terraform plan
        workingDirectory: $(TF_ROOT)

      - bash: terraform show -json tfplan.binary > plan.json
        displayName: Terraform show
        workingDirectory: $(TF_ROOT)

      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(apiKey)

      - bash: infracost breakdown --path=plan.json --format=json --out-file=/tmp/infracost.json
        displayName: Run Infracost

      - task: InfracostComment@0
        displayName: Post the comment
        inputs:
          path: /tmp/infracost.json
          behavior: update # Create a single comment and update it. See https://github.com/infracost/infracost-azure-devops#comment-options for other options