# The Azure Pipelines docs (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks) describe other options.
# Running on pull requests to `master` (or your default branch) is a good default.
pr:
  - master

variables:
  - name: TF_ROOT
    value: terraform # Update this!

jobs:
  - job: infracost
    displayName: Run Infracost
    pool:
      vmImage: ubuntu-latest

    steps:
        # Typically the Infracost actions will be used in conjunction with the Terraform tool installer task
        # If this task is not available you can add it to your org from https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks.
        # Subsequent steps can run Terraform commands as they would in the shell.
      - task: TerraformInstaller@0
        displayName: Install Terraform

      # IMPORTANT: add any required steps here to setup cloud credentials so Terraform can run

      - bash: terraform init
        displayName: Terraform init
        workingDirectory: $(TF_ROOT)

      - bash: terraform plan -out tfplan.binary
        displayName: Terraform plan
        workingDirectory: $(TF_ROOT)
        env:
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          ARM_TENANT_ID: $(ARM_TENANT_ID)
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

      - bash: terraform show -json tfplan.binary > plan.json
        displayName: Terraform show
        workingDirectory: $(TF_ROOT)

      # Install the Infracost CLI, see https://github.com/infracost/infracost-azure-devops#infracostsetup
      # for other inputs such as version, and pricingApiEndpoint (for self-hosted users).
      - task: InfracostSetup@0
        displayName: Setup Infracost
        inputs:
          apiKey: $(INFRACOST_API_KEY)

      # Run Infracost and generate the JSON output, the following docs might be useful:
      # Multi-project/workspaces: https://www.infracost.io/docs/features/config_file
      # Combine Infracost JSON files: https://www.infracost.io/docs/features/cli_commands/#combined-output-formats
      - bash: infracost breakdown --path=$(TF_ROOT)/plan.json --format=json --out-file=/tmp/infracost.json --usage-file $(TF_ROOT)/infracost-usage.yml
        displayName: Run Infracost

      # See https://github.com/infracost/infracost-azure-devops#infracostcomment for other options
      - task: InfracostComment@0
        displayName: Post Infracost comment
        inputs:
          githubToken: $(GITHUB_TOKEN) # Required to post comments
          path: /tmp/infracost.json
          # Choose the commenting behavior, 'update' is a good default:
          behavior: update # Create a single comment and update it. The "quietest" option.
          # behavior: delete-and-new # Delete previous comments and create a new one.
          # behavior: hide-and-new # Minimize previous comments and create a new one.
          # behavior: new # Create a new cost estimate comment on every push.
          # Limit the object that should be commented on, either merge-request or commit
          # targetType: pull-request
