pool:
  vmImage: ubuntu-latest


variables:
- group: KeyVaultVariableGroups


stages:
  - stage: infracost
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs: 
      - job: infracost
        displayName: Run Infracost
        steps:
          - checkout: self
          - bash: |
              sudo apt-get update -qq && sudo apt-get -qq install bc curl git
              curl -sL https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz | tar xz -C /tmp
              sudo mv /tmp/infracost-linux-amd64 /usr/bin/infracost
              curl -sL -o infracost_diff.sh https://raw.githubusercontent.com/infracost/infracost/master/scripts/ci/diff.sh
              chmod +x infracost_diff.sh
              ./infracost_diff.sh
            displayName: Run Infracost diff
            env:
              INFRACOST_API_KEY: $(INFRACOST_API_KEY)
              GITHUB_TOKEN: $(GITHUB_TOKEN)
              ARM_SUBSCRIPTION_ID: $(kv-arm-subscription-id)
              ARM_CLIENT_ID:       $(kv-arm-client-id)
              ARM_CLIENT_SECRET:   $(kv-arm-client-secret)
              ARM_TENANT_ID:       $(kv-arm-tenant-id)
              path: terraform        
