pool:
  vmImage: ubuntu-latest

stages:
  - stage: infracost
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs: 
      - job: infracost
        displayName: Run Infracost
        steps:
          - checkout: self
          - bash: |
              sudo apt-get update -qq && sudo apt-get -qq install bc curl git
              curl -sL https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz | tar xz -C /tmp
              sudo mv /tmp/infracost-linux-amd64 /usr/bin/infracost
              curl -sL -o infracost_diff.sh https://raw.githubusercontent.com/infracost/infracost/feat/github_pr_comments/scripts/ci/diff.sh
              chmod +x infracost_diff.sh
              ./infracost_diff.sh
            displayName: Run Infracost diff
            env:
              INFRACOST_API_KEY: $(INFRACOST_API_KEY)
              GITHUB_TOKEN: $(GITHUB_TOKEN)
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              path: terraform
              post_condition: { "update": true }
